package com.example.MyApp.Model;

import jakarta.persistence.*;

import java.util.List;

@Entity
@Table(name = "accounts")
public class Account {
    public Account(){

    }
    public Account(String fullNameField, String emailField, String mobileNumberField, String addressField) {

        this.fullNameField = fullNameField;
        this.emailField = emailField;
        this.mobileNumberField = mobileNumberField;
        this.addressField = addressField;
    }

    @Id
    @GeneratedValue(strategy =  GenerationType.IDENTITY) // ID is generated by the database when you save the entity.
    @Column(name = "ID", nullable = false)
    private Integer id;

    @Column(name = "Name", nullable = false)
    private String fullNameField;

    @Column(name = "Email", nullable = false)
    private String emailField;

    @Column(name = "Mobile",unique = true, nullable = false)
    private String mobileNumberField;

    @Column(name = "Address", nullable = false)
    private String addressField;

    @Column(name = "accountnumber",unique = true, nullable = false)
    private Integer accountNumber;

    @Column(name = "Balance", nullable = false)
    private Integer balance;


    @OneToMany(mappedBy = "Linkedaccno")
    private List<Beneficiary> beneficiaries;

    @Override
    public String toString() {
        return "Account{" +
                "id=" + id +
                ", fullNameField='" + fullNameField + '\'' +
                ", emailField='" + emailField + '\'' +
                ", mobileNumberField='" + mobileNumberField + '\'' +
                ", addressField='" + addressField + '\'' +
                ", accountNumber=" + accountNumber +
                ", balance=" + balance +
                '}';
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getBalance() {
        return balance;
    }

    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    public Integer getAccountNumber() {
        return accountNumber;
    }

    public void setAccountNumber(Integer accountNumber) {
        this.accountNumber = accountNumber;
    }


    public String getAddressField() {
        return addressField;
    }

    public void setAddressField(String addressField) {
        this.addressField = addressField;
    }

    public String getMobileNumberField() {
        return mobileNumberField;
    }

    public void setMobileNumberField(String mobileNumberField) {
        this.mobileNumberField = mobileNumberField;
    }

    public String getEmailField() {
        return emailField;
    }

    public void setEmailField(String emailField) {
        this.emailField = emailField;
    }

    public String getFullNameField() {
        return fullNameField;
    }

    public void setFullNameField(String fullNameField) {
        this.fullNameField = fullNameField;
    }

    public List<Beneficiary> getBeneficiaries() {
        return beneficiaries;
    }

    public void setBeneficiaries(List<Beneficiary> beneficiaries) {
        this.beneficiaries = beneficiaries;
    }

}
